### PR TITLE
USE UTF-8 TO DECODE EVERYTHING AS ANY OTHER MODS DOES!

### PR DESCRIPTION
**Pull request by xinyuan-liu**
Use UTF-8 to decode text files as Minecraft and ALL other mods does.
You should designating the charset when reading files. Otherwise Java will use the system default charset which may vary with different systems or locations.
That should finally fix
https://github.com/Electroblob77/Wizardry/issues/440
https://github.com/Electroblob77/Wizardry/issues/406
https://github.com/Electroblob77/Wizardry/issues/404

### CODE REVIEW

**Comment by xinyuan-liu** [comment]
I've checked that all the handbook files are encoded in UTF-8 now so this pull request should solve all related issues.

**Comment by Electroblob77** [comment]
Thanks for fixing this. My editor is always set to UTF-8 so it's the authors of translations that have used different encoding, I'll add a note in the contributing guide so they know to use the right settings.

Also, I don't think this PR covers the use of `InputStreamReader` here:
https://github.com/Electroblob77/Wizardry/blob/eb017c01a9e1ee86089a8bc27bcfa5a346c1d59b/src/main/java/electroblob/wizardry/client/gui/GuiSpellDisplay.java#L365-L371
Could you add it there as well? Thanks.

**Comment by xinyuan-liu** [comment]
Ok I've added it. Decoding issues are really common issues puzzling many modders and translators.

**Comment by Electroblob77** [comment]
Great, thanks

**Pull request merged**
