### PR TITLE
Try to fix lighting web concurrent modification

### PR DESCRIPTION
**Pull request by SettingDust**
Related: #567 #513
Try to fix. Not sure is it working now.
Just instead the sublist and for in with stream api

### CODE REVIEW

**Comment by Electroblob77** [comment]
I appreciate the effort to try and fix the bug, thank you, but as with the other PR, please update your fork of the repo before submitting. I'll leave this open as I'm happy to merge these changes for an up-to-date file.

**Comment by SettingDust** [comment]
For the same reason. I was rebased on 1.12.2-dev :(

**Comment by SettingDust** [comment]
> I appreciate the effort to try and fix the bug, thank you, but as with the other PR, please update your fork of the repo before submitting. I'll leave this open as I'm happy to merge these changes for an up-to-date file.

Done.

**Comment by Electroblob77** [comment]
Great, thanks!

**Pull request merged**
